// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIQkIE-HlSu2Fc1Tfu2FSDKiuH_PJp7E',
    appId: '1:1040815219870:web:b9c259a086e17856ef878f',
    messagingSenderId: '1040815219870',
    projectId: 'cells27',
    authDomain: 'cells27.firebaseapp.com',
    storageBucket: 'cells27.appspot.com',
    measurementId: 'G-744QB03PP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaaVCvAN7bqL3OzNjauRA7QKUjQu_REsw',
    appId: '1:1040815219870:android:64f597af5332a92eef878f',
    messagingSenderId: '1040815219870',
    projectId: 'cells27',
    storageBucket: 'cells27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWSgsJVNcrzLxiNJwRWXSUKP7dK46LKA',
    appId: '1:1040815219870:ios:286d55c3c76fd74fef878f',
    messagingSenderId: '1040815219870',
    projectId: 'cells27',
    storageBucket: 'cells27.appspot.com',
    iosClientId:
        '1040815219870-8ag3937s9u5eubp2g63svbk1rdlig2ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.cells',
  );
}
